docs/docs/documentation/concepts/gateways.md, docs/docs/documentation/concepts/plugins/index.md, docs/docusaurus.config.ts
The purpose of this change is to update the URLs for the official core plugins of the Solace Agent Mesh documentation to reflect the new repository location. This ensures users are directed to the correct resources for accessing and utilizing the plugins.
- Updated urls for solace-agent-mesh-core-plugins
Reviewers should ensure that all instances of the outdated URLs have been correctly updated to the new SolaceLabs repository URLs.
=> DOCS: Update URLs for Solace Agent Mesh Core Plugins

cli/commands/build.py, src/gateway/components/gateway_input.py, src/orchestrator/orchestrator_prompt.py, templates/gateway-config-template.yaml, templates/gateway-default-config.yaml, templates/gateway-flows.yaml, templates/rest-api-default-config.yaml, templates/rest-api-flows.yaml, templates/slack-default-config.yaml, templates/slack-flows.yaml, templates/web-default-config.yaml, templates/web-flows.yaml
1. Allow a user to put the response_format_prompt in either the gateway or interface configuration and if it isn't there, then insert a default value.
2. Add a bit more information into the orchestrator prompt to indicate how to handle report requests
This should be backwards compatible
=> AI-558: Improve the configurability of the response_format_prompt

docs/docs/documentation/tutorials/sql-database.md
Add an easy tutorial to add some data into the system so that you can do interesting things with Agent Mesh
Tutorial has been added here and sample data has been added to the sam-sql-database agent plugin
=> AI-566: Add a tutorial for adding an SQL plugin (with sample data)

pyproject.toml, src/services/llm_service/components/llm_request_component.py
Handling Litellm errors
Any messages having `handle_error` key set to True will return their payload's content to the orchestrator.
This is a multi-repository change. The change itself does not affect anything yet since message payloads do not include the `handle_error` key.
=> AI-308: Handle litellm errors

src/orchestrator/components/orchestrator_stimulus_processor_component.py, src/services/middleware_service/middleware_service.py
Fix the issue with user information being "unknown" after opening an agent. This will fix the issues with SAM asking for the users email for tasks such as looking up jira issues etc
Instead of getting user properties from the data object we get it from the message object which always has it
=> AI-548: Fix orchestrator asking for email bug

cli/commands/init/init.py
Instead of serving web ui on localhost, we use 127.0.0.1, in rare cases we saw some CORS issues due to this.
=> AI-615: Fix rare CORS issue due to using localhost 

configs/monitor_stim_and_errors_to_slack.yaml, src/agents/base_agent_component.py, src/common/action_response.py, src/common/constants.py, src/orchestrator/action_manager.py, src/orchestrator/components/orchestrator_stimulus_processor_component.py
To prevent the orchestrator from processing action responses that were not initiated by the orchestrator itself, by introducing a way to identify and ignore these external responses.
By adding a special identifier ('non-orchestrator-agent-invocation') to the action_list_id field for actions initiated outside the orchestrator, and modifying the action_manager to check for and ignore responses with this identifier. This was implemented in both the configuration file and the action manager's response handling logic.
Reviewers should verify that legitimate orchestrator-initiated actions continue to work normally while external actions are properly ignored. This change affects action response routing, so it's important to confirm there are no unintended side effects on the overall messaging …
=> AI-436: Prevent orchestrator from processing action responses not initiated by orchestrator

src/agents/global/actions/plotly_graph.py, src/agents/web_request/actions/do_web_request.py, src/orchestrator/orchestrator_prompt.py
Make examples llm agnostic, so that in the future they can be easily rendered in another format for example markdown for open ai. 
Before passing in the exampls we convert them based on the given llm_type.
=> AI-643: Make examples llm agnostic

README.md, docs/docs/documentation/getting-started/quick-start.md, docs/docs/documentation/tutorials/sql-database.md
This is being done because we recently switched the Web UI host to 127.0.0.1 from localhost, this was done because in rare cases there would be CORS errors. This is the documentation update for that change. Reference: #31
=> Update documentation for web UI to use 127.0.0.1 instead of localhost

cli/commands/add/gateway.py, cli/commands/init/create_other_project_files_step.py
This PR adds the capability to overwrite environment variables in .env files during the sam init command
1. Added capability to overwrite environment variables in .env files to prevent duplicating environment variables
=> AI-663: Add ability to overwrite env vars in .env during sam init

src/services/history_service/history_providers/sql_history_provider.py
The purpose of this change is to address a minor bug in the SQL provider where the retrieval of session data was not handled correctly, potentially resulting in incorrect data processing or application errors.
- Minor bug in SQL provider
The solution involves checking if the fetched row's data field exists and handling it appropriately, ensuring the data is correctly loaded into a dictionary format, and adding a debug print statement to verify the fetched data.
Reviewers should ensure that the changes correctly handle empty or malformed session data and that the added debug statement is useful or necessary.
=> AI-714: Fix minor bug in SQL provider

src/services/history_service/history_providers/index.py, src/services/history_service/history_service.py
The purpose of this change is to implement a lazy loaded factory pattern for history providers, enhancing the modularity and flexibility of the history service. This allows for dynamic loading of specific history provider classes based on the configuration, reducing unnecessary dependencies and improving maintainability.
- Added lazy loaded factory pattern to history provider.
- Introduced the `HistoryProviderFactory` class to manage different history providers and their instantiations.
- Modified the existing code to utilize the factory for obtaining history provider instances instead of importing all providers upfront.
Reviewers should focus on the integration of the factory pattern with the existing history service logic, ensuring that the dynamic loading does not affect the service's …
=> AI-729: Implement lazy loading pattern in history provider

pyproject.toml
The purpose of this change is to ensure compatibility with Python 3.10 environments, which might have been previously overlooked or unsupported in the testing configuration.
- Quick fix for python 3.10 env
The modification involves updating the testing matrix in the project configuration to include Python 3.10.
Ensure that adding Python 3.10 to the testing matrix does not inadvertently affect existing workflows or compatibility checks.
=> FIX: Update compatibility for Python 3.10 environment

cli/commands/add/copy_from_plugin.py, cli/commands/plugin/build.py
Plugins that are instantiated via solace-agent-mesh.yaml need to have the name placeholders substituted just like they are for --copy-from
Changes in build.py
=> AI-658: Fix to do substitutions on build for plugins

src/orchestrator/orchestrator_prompt.py
This PR reverts changes made to the system prompt while retaining the fix for action history. The goal is to revert to the previous prompt structure while keeping improvements to how action history is handled.
- Reverting the system prompt and only keeping action history fix
Ensure the action history fix is maintained while the system prompt structure reverts to its previous form.
=> FIX: Fix action history while reverting system prompt changes

README.md, cli/commands/run.py, cli/main.py, docs/docs/documentation/concepts/cli.md, docs/docs/documentation/deployment/debugging.md, docs/docs/documentation/deployment/deploy.md, docs/docs/documentation/getting-started/quick-start.md, docs/docs/documentation/tutorials/event-mesh-gateway.md, docs/docs/documentation/tutorials/mcp-integration.md, docs/docs/documentation/tutorials/slack-integration.md, docs/docs/documentation/tutorials/sql-database.md, docs/docs/documentation/user-guide/custom-agents.md, docs/docs/documentation/user-guide/custom-gateways.md
This changes the `sam run` command to utilize the `.env` file by default. For deployment purposes where users might prefer using system environment variables over the .env file, there is a new option `-u` or `--use-system-env` which will prefer the system environment over the .env file.
In cases where `sam run` is called but there is no `.env` file we already automatically use the system environment, I have made no changes to this behavior.
This PR also contains all the documentation changes for the new option + removing references to the `-e` option
Changing the run command.
Reviewers should ensure documentation is updated properly and the new option works as expected
=> AI-709: Use .env file by default and introduce new option -u

configs/orchestrator.yaml, src/orchestrator/components/orchestrator_action_manager_timeout_component.py, src/orchestrator/orchestrator_main.py
1. When agent registration messages have not be received for 60s, the agent must be removed from the list of available agents
2. If an agent of the same name registers with different configuration, then the new config must be used. This will happen on upgrades and during dev work
1. The agent age out method and tracking all already existed. We just needed to hook a call into it in a place where it would be called periodically. This was done in the action response timer handler
2. The orchestrator config file had a very long timeout (60k seconds). This was changed to 60s, which means 4 registrations would need to be missed before removing the agent
3. Previously, we would not update agent configuration when registering the agent. Now we always take the config from the last registration, …
=> AI-660: Agent registry must support expiration and config updates

README.md, cli/commands/init/init.py, docs/docs/documentation/getting-started/quick-start.md, docs/docs/documentation/tutorials/sql-database.md, docs/docs/documentation/user-guide/advanced/advanced-configuration/web-ui.md
This is the documentation update that goes along with this PR https://github.com/SolaceLabs/solace-ai-connector-web/pull/16. It also updates the default host for the web ui to be `localhost`
=> AI-657: Fix localhost CORS bug with web ui

.github/workflows/ci.yaml, pyproject.toml
- set min and max versions correctly 3.10.16 and 3.13
=> DATAGO-98396: relax min python requirement to 3.10.16

.github/helper_scripts/build_frontend.py, pyproject.toml
- install npm deps and build the UI on `hatch build`
=> DATAGO-99407: add custom build hook for config_portal build

src/agents/global/actions/plotly_graph.py, src/common/utils.py, src/orchestrator/components/orchestrator_stimulus_processor_component.py, src/orchestrator/orchestrator_prompt.py
Make the Gemini 2.5 model work well with SAM
There were a few things that needed changing:
1. In the file directives of the orchestrator prompt, it was possible that the model would add t###_ to the internal tags. We now are okay if that happens
2. There were a number of places where parameters would have their whitespace stripped. This was wrong and has been removed
3. Be strict about needing <t### _reasoning> in the response. Gemini occasionally gives a crazy response, which we should error on
4. Handle action parameters being surrounded by CDATA or having XML entities in them.
5. Fix plotly graph examples to not have double curly braces
6. Look for errors in the parsing and reinvoke the orchestrator based on that
7. Explicitly tell the orchestrator to not put ```xml around the response …
```
=> AI-696: Adjust the orchestrator to work well with Gemini 2.5

cli/commands/add/agent.py, cli/commands/add/copy_from_plugin.py, cli/commands/add/gateway.py, cli/commands/plugin/create.py
To update the plugin creation process to follow Git conventions by using `.gitkeep` files instead of custom named placeholder files for empty directories.
- Update emtpy file to use git convensions
- Changed placeholder files from custom names (`__TEMPLATES_WILL_BE_HERE__`, `__INTERFACES_WILL_BE_HERE__`) to standard `.gitkeep`
- Removed the explicit message in empty files that previously explained their purpose
This is a simple convention change that doesn't affect functionality but improves adherence to standard Git practices.
=> ENHANCE: Add proper Git conventions to empty file

config_portal/frontend/app/common/providerModels.ts, config_portal/frontend/app/components/steps/AIProviderSetup.tsx, config_portal/frontend/app/components/steps/CompletionStep.tsx
This came up in testing where if the user provides the model name as `openai/<model_name>`in the init GUI then when they submit another `openai/` is added to this causing the model name to be `openai/openai/<model_name>`
=> AI-791 : Init GUI should not add provider/ if already provided by the user

src/services/history_service/history_providers/sql_history_provider.py
This change fixes a potential memory error that could occur when retrieving a non-existent session from the SQL history provider.
- Added slight fix for memory by modifying the `get_session` method to check if `row` exists before accessing its data
This is a small defensive coding fix to prevent accessing attributes on a None object when no session is found.
=> FIX: Fix memory issues

cli/commands/plugin_cmd/official_registry.py, config_portal/backend/plugin_catalog/constants.py
Update the Git branch used for the official registry in the plugin catalog from 'dev' to 'main', ensuring that the plugin catalog points to the stable main branch of the Solace Agent Mesh core plugins repository.
- Update official registry Git branch to main
Verify that the main branch of the repository contains the expected stable content for production use.
=> PLUGINS-PATH: Update official registry Git branch to main

config_portal/frontend/app/components/AddAgentFlow.tsx, src/solace_agent_mesh/agent/tools/general_agent_tools.py
This change fixes a bug that prevented users from removing built-in group tools when configuring an agent.
- Fix bug of not being able to remove built-in group tools by simplifying the tool initialization logic
- Replace the conditional logic that was always adding default tools back (preventing their removal) with a simpler approach that only adds the artifact management tool by default
The PR maintains default artifact management tools while allowing other built-in group tools to be removable. Verify this doesn't cause unexpected behavior in the agent creation flow.
=> BUGS: Fix bug preventing removal of built-in group tools

client/webui/frontend/src/lib/components/activities/FlowChart/taskToFlowData.ts
The message of User Request and LLM request almost happens at the same time. 
Because they have the different timestamp source, it could results LLM request happens a couple of millisecond ahead of User Request, which causes LLM node is not created in the flowchart as it depends on the User node first.
Before the timestamp issue is solved, this change manually put the User Request step as the first step in a task step array to fix the missing LLM node in some cases.
=> Fix an issue with missing LLM requests caused by timestamp

cli/commands/run_cmd.py
Re-configuring the logging after solace ai connector startup
Calling the reconfigure logging once the `run` command is called
This change goes hand to hand with another change in the solace-ai-connector repo
Does not rely on the changes to solace-ai-connector
=> DATAGO-108430: Fix log level stdio configuration

cli/commands/add_cmd/web_add_agent_step.py, cli/commands/add_cmd/web_add_gateway_step.py, cli/commands/init_cmd/web_init_step.py, cli/commands/plugin_cmd/catalog_cmd.py, cli/utils.py, config_portal/backend/common.py, docs/docs/documentation/tutorials/custom-agent.md
This PR improves server readiness handling in the CLI and fixes documentation numbering errors. The changes enhance reliability by implementing consistent server readiness checks across various web portal commands and corrects step numbering in the custom agent tutorial for a better user experience.
- feat: implement wait_for_server utility for improved server readiness checks
- Created a centralized wait_for_server utility function in cli/utils.py that all web portal commands now use
- Replaced ad-hoc waiting mechanisms (sleep calls) with the more reliable server readiness check
- Applied the utility consistently across add agent, add gateway, init, and plugin catalog commands
- fix: correct step numbering in custom agent tutorial for clarity
- Fixed inconsistent step numbering in the …
=> MINOR-FIXES: Fix step numbering in custom agent tutorial and add wait_for_server utility

client/webui/frontend/src/lib/components/chat/ChatSessionDeleteDialog.tsx, client/webui/frontend/src/lib/components/chat/SessionList.tsx, client/webui/frontend/src/lib/components/pages/ChatPage.tsx, client/webui/frontend/src/lib/hooks/index.ts, client/webui/frontend/src/lib/hooks/useAgentCards.ts, client/webui/frontend/src/lib/hooks/useSessionPreview.ts, client/webui/frontend/src/lib/providers/ChatProvider.tsx
This PR:
* removes lint warnings in session support
* updates the sessions UI to be more consistent with Solace styles and components
https://github.com/user-attachments/assets/b09ed6ca-25bd-4968-9472-ac844b199301
Note: there is an outstanding bug around chat session naming - they are inconsistent between side panel, chat and dialog.
=> chore(DATAGO-111340): tidying session ui (part 1)

cli/commands/run_cmd.py, config_portal/backend/plugin_catalog/registry_manager.py
This pull request addresses issue #262 by fixing filepath handling in the registry manager and implementing registry name sanitization to ensure filesystem compatibility.
- fix(registry_manager): Cleaned file path and sanitize registry names.
- Improved display of file paths in the run command by removing the unnecessary conversion to relative paths
- Added proper UTF-8 encoding when reading/writing registry files
- Added sanitization of registry names to ensure they're filesystem-friendly by converting non-alphanumeric characters to underscores
The registry name sanitization implementation converts all non-alphanumeric characters to underscores. Reviewers should consider if this approach is sufficient or if a more nuanced sanitization might be needed for certain use cases.
=> BUG-FIXES: fix(registry_manager): Clean file paths and sanitize registry names

src/solace_agent_mesh/gateway/http_sse/app.py, src/solace_agent_mesh/gateway/http_sse/component.py, src/solace_agent_mesh/gateway/http_sse/sse_event_buffer.py, src/solace_agent_mesh/gateway/http_sse/sse_manager.py
It seems to be possible sometimes for an agent to send events back to the user before the SSE connection is established for that task. We need to buffer those events until the SSE connection arrives
=> fix(DATAGO-111703): Buffer task events that arrive in the gateway before the frontend creates an SSE connection

cli/commands/plugin_cmd/__init__.py, cli/commands/plugin_cmd/add_cmd.py, cli/commands/plugin_cmd/install_cmd.py, docs/docs/documentation/concepts/cli.md
This change adds a new `install` command to the plugin management system, making it easier to install SAM plugins from various sources without directly creating a component. It also refactors the existing installation logic to make it reusable between the `add` and `install` commands.
- feat(plugin): add install command and update documentation
- Extract plugin installation logic from `add_cmd.py` into a new reusable function in `install_cmd.py`
- Create a new CLI command `sam plugin install` that allows installing plugins without creating components
- Update the plugin add command to use the shared installation logic
- Update documentation to include the new command
The refactoring maintains existing functionality while providing a cleaner separation of concerns. Verify that both …
=> PLUGIN-INSTALL: feat(plugin): add install command and update documentation

client/webui/frontend/src/lib/components/chat/ChatMessage.tsx, client/webui/frontend/src/lib/components/chat/preview/Renderers/MermaidRenderer.tsx
Made Mermaid diagrams larger by default and made them resizable
=> feat(DATAGO-111479): Improve Mermaid diagram Rendering

src/solace_agent_mesh/agent/sac/app.py
Issue:
Display names were never being returned to the FE.
Fix: 
It was traced it back to it never returning in the app config despite being in the YAML configuration. It seems that it was missing from the app configuration and thus never populated.
=> fix(DATAGO-111345): adding display name to sam agent definition

src/solace_agent_mesh/agent/sac/app.py, src/solace_agent_mesh/agent/sac/component.py
**Problem:**
The _agent_init_function_ in config files are ignored because the object type of this tag is not dictionary. This type has been defined in agent/sac/app.py -> SamAgentAppConfig class.
=> fix(DATAGO-112069): update the type checking

client/webui/frontend/src/lib/components/header/Header.tsx, client/webui/frontend/src/lib/components/ui/button.tsx, client/webui/frontend/src/lib/components/ui/index.ts, client/webui/frontend/src/lib/components/ui/pagination.tsx
This pull request introduces a new reusable pagination component to the UI library and improves the flexibility and consistency of button components. The main changes include adding the pagination component and its exports, refactoring button types for better type safety, and making minor UI adjustments.
**UI Library Additions:**
* Added a new pagination component with supporting elements (`Pagination`, `PaginationContent`, `PaginationLink`, `PaginationItem`, `PaginationPrevious`, `PaginationNext`, `PaginationEllipsis`) in `pagination.tsx` for consistent pagination controls across the app.
* Exported the new pagination components from the UI library index file (`ui/index.ts`) to make them available for use throughout the project.
**Button Component Improvements:**
* Refactored the button …
=> chore(DATAGO-111334): Add Pagination ui component

.gitignore, src/solace_agent_mesh/agent/sac/component.py
- fixed tool origin extraction, currently this affects enterprise since RBAC is not enforced.
=> DATAGO-112640 - RBAC not working due to scopes not enforced on tools

src/solace_agent_mesh/agent/sac/app.py, src/solace_agent_mesh/agent/utils/artifact_helpers.py, src/solace_agent_mesh/common/constants.py
**Goal:**
- Increased the maximum and default capacity of loading artifacts to 200K and 100K respectively.
- Added 'message-to-llm' data field to lead the LLM
=> DATAGO-110479: update the maximum capacity of loading artifacts

cli/commands/plugin_cmd/create_cmd.py, cli/commands/plugin_cmd/plugin_cmd_llm.txt, templates/plugin_pyproject_template.toml
This change removes SAM version references from plugin creation and template files to eliminate unnecessary version coupling between plugins and the SAM framework.
- fix: remove SAM version references from plugin creation and template files
- Removed `__SAM_VERSION__` from the replacements dictionary in `create_plugin_cmd.py`
- Removed reference to `__SAM_VERSION__` in the plugin command LLM documentation
- Removed the `solace_agent_mesh~=__SAM_VERSION__` dependency from the plugin pyproject template
Ensure that removing these version references doesn't break any existing plugin creation or functionality processes.
=> fix(DEP): remove SAM version references from plugin creation and template files

src/solace_agent_mesh/common/services/identity_service.py, src/solace_agent_mesh/common/services/providers/local_file_identity_service.py, src/solace_agent_mesh/gateway/base/component.py, tests/integration/scenarios_programmatic/test_services.py
This change adds the ability to pass a component parameter to identity service implementations, allowing identity service providers to access component resources and configuration when needed. This enhances the flexibility and integration capabilities of identity services within the agent mesh architecture.
- feat: add component parameter to identity service and local file identity service initialization
- Updated the BaseIdentityService class to accept an optional component parameter
- Modified the create_identity_service factory function to pass the component to service implementations
- Updated the LocalFileIdentityService implementation to support the component parameter
- Added test cases to verify the proper handling of the component parameter
Verify that existing identity service …
=> feat(DATAGO-113298): Add component parameter to identity service and local file identity service initialization

src/solace_agent_mesh/agent/adk/artifacts/s3_artifact_service.py, src/solace_agent_mesh/agent/adk/services.py
Error happens when both memory and s3 artifact services are selected in different agents. The memory fields were leaking in the `s3_config` dict.
Fixed by restricting the fields inside the `s3_config` dict.
=> fix(DATAGO-113843): Fixed s3 init artifact service
