- .github/workflows/gh_pages.yaml
- docs/docs/index.md
The purpose of this change is to address issues within the GitHub Pages workflow configuration, ensuring that the documentation is correctly built and deployed automatically. This enhances the reliability and efficiency of maintaining and updating project documentation.
- added fix for github page workflow
Important changes include updating the workflow name to "Github Pages," adding the `workflow_dispatch` trigger, updating the version of the `upload-pages-artifact` action, and removing an obsolete index markdown file from the documentation directory.
Reviewers should ensure the updated workflow configuration accurately reflects the intended deployment process and verify the compatibility with the updated action versions.
> PAGE: Fix GitHub Pages Workflow

- .github/workflows/gh_pages.yaml
- README.md
- docs/docusaurus.config.ts
The purpose of this change is to update and improve the GitHub Pages deployment workflow and documentation links for better accuracy and reliability. This ensures that the latest documentation is correctly built and deployed, and that all links point to the correct locations.
- Updated docs locations
- Added fix for GitHub Pages workflow
- Changed artifact upload and deployment actions in the workflow
- Merged latest changes from the main branch into the feature branch
Ensure that the updated links in the documentation are correct and that the GitHub Pages deployment workflow functions as intended.
> AI-512: Fix for GitHub Pages workflow and updated documentation locations

- docs/docs/documentation/concepts/agents.md
- docs/docs/documentation/concepts/cli.md
- docs/docs/documentation/concepts/gateways.md
- docs/docs/documentation/concepts/orchestrator.md
- docs/docs/documentation/getting-started/installation.md
- docs/docs/documentation/getting-started/quick-start.md
- docs/docs/documentation/tutorials/event-mesh-gateway.md
- docs/docs/documentation/tutorials/mcp-integration.md
- docs/docs/documentation/tutorials/slack-integration.md
- docs/docs/documentation/user-guide/advanced/overwrites.md
- docs/docs/documentation/user-guide/advanced/services/file-service.md
- docs/docs/documentation/user-guide/advanced/services/history-service.md
- docs/docs/documentation/user-guide/cli-chat.md
- docs/docs/documentation/user-guide/custom-agents.md
Reapply some of the changes that were missed.
Editing the MD files
The changes are mostly the branding changes documented at https://sol-jira.atlassian.net/wiki/spaces/DT/pages/4888920357/Solace+Agent+Mesh+Branding.
I'd like to compare to the original changes I made as I can see some didn't make it over from the Cyrus' branch. It could be a me problem.
> DOC-6044-Redo branding changes and fix CLI

- docs/docs/documentation/tutorials/mcp-integration.md
- docs/docs/documentation/tutorials/slack-integration.md
> DOC-6044-Edits

- .github/workflows/ci.yaml
- .github/workflows/release.yml
- pyproject.toml
> Include web_visualizer into build wheel

- cli/commands/build.py
- docs/docs/documentation/tutorials/sql-database.md
- src/gateway/components/gateway_input.py
- src/orchestrator/orchestrator_prompt.py
- templates/gateway-config-template.yaml
- templates/gateway-default-config.yaml
- templates/gateway-flows.yaml
- templates/rest-api-default-config.yaml
- templates/rest-api-flows.yaml
- templates/slack-default-config.yaml
- templates/slack-flows.yaml
- templates/web-default-config.yaml
- templates/web-flows.yaml
* Improved report generation through orchestrator prompt refinements
* More flexible way to configure the response_format_prompt - this can be specified in either a gateway config or interface config (or neither)
* Tutorial for SQL Database plugin
> Create release 0.1.2 

- src/common/postgres_database.py
Make postgres instance initialization configurable
added a default param.
> AI-597: Make postgres instance initialization configurable 

- pyproject.toml
> Chore: Upgrade web version

- Makefile
- cli/commands/plugin/add.py
- cli/commands/plugin/plugin.py
- cli/commands/plugin/remove.py
- docs/docs/documentation/concepts/cli.md
The purpose of this change is to address and fix minor issues related to package installation tools and configurations, ensuring consistency and correctness in the build and plugin commands.
- The `pip` references were updated to use `pip3` to ensure compatibility with Python 3.
- The installation options for plugins were refined by replacing `uv-pip` with `uv`, simplifying the command interfaces.
- The `Makefile` was updated to use `hatch build` instead of `python3 -m build` for building the package.
Reviewers should focus on ensuring that the changes do not disrupt the existing workflow and that the new commands properly execute the intended actions without errors.
> AI-557: Improve pip and build process by fixing minor details

- src/gateway/components/gateway_output.py
- src/services/history_service/history_providers/base_history_provider.py
- src/services/history_service/history_providers/memory_history_provider.py
- src/services/history_service/history_providers/redis_history_provider.py
- src/services/history_service/history_service.py
The change aims to enhance the functionality of clearing history by introducing the capability to also clear associated files. This ensures a more comprehensive cleanup, addressing user requests to manage and streamline stored data effectively.
- Clearing file history on clear history action
Ensure that the implementation correctly handles the option to clear files and maintains expected behavior for different storage providers.
> AI-439: Implement clear history action to reset file history

- docs/docs/documentation/tutorials/sql-database.md
Small change to be more clear about which directory you should be putting your files in for the sql tutorial.
> Update SQL tutorial documentation

- pyproject.toml
Updating Solace dependencies to latest versions.
> Release 0.1.3: Update Solace dependencies to latest versions

- src/common/utils.py
- src/services/file_service/file_service.py
- src/services/file_service/file_transformations.py
- src/services/file_service/file_utils.py
Make Solace Chat output more resilient
Handling edge cases
Decoding byte files
> AI-646: Fixing small bugs raised from feedback or status channel

- pyproject.toml
> Release: Upgrade web version to latest

- src/agents/global/actions/plantuml_diagram.py
- src/agents/image_processing/actions/describe_image.py
- src/agents/web_request/actions/do_web_request.py
Handle Timeout errors in two actions: plantuml and web_request
Catching properly the errors
> AI-681: Handle timeout in actions

- .dockerignore
- .gitignore
- docs/docs/documentation/user-guide/advanced/services/history-service.md
- src/services/history_service/history_providers/sql_history_provider.py
- src/services/history_service/history_service.py
- src/services/history_service/long_term_memory/long_term_memory.py
The purpose of this change is to address compatibility issues with Python 3.11 and to enhance the system's functionality by adding a new SQL-based history provider. The changes aim to ensure that the application can run smoothly with the latest Python update and to provide a more robust way of storing session history in SQL databases, thereby improving data management and retrieval efficiency.
- Fixed python 3.11 issues
- Added SQL History Provider
Reviewers should focus on the integration of the SQL History Provider and ensure that it interacts correctly with existing systems, particularly considering different database backends (PostgreSQL and MySQL). Additionally, verify that the changes remain compatible with Python 3.11.
> AI-714: Add SQL History Provider and resolve Python 3.11 compatibility issues

- pyproject.toml
Fix release action
Add 3.13 to hatch-test matrix
> AI-730: Add 3.13 to hatch-test matrix

- .github/workflows/ci.yaml
- pyproject.toml
- fix release job to use correct python version
> fix min version for release

- docs/docs/documentation/user-guide/advanced/services/history-service.md
- src/orchestrator/orchestrator_prompt.py
This PR improves system documentation accuracy and enhances the orchestrator system prompt with clearer instructions and better formatting, while also removing outdated test code.
- Enhanced system prompt with latest history changes
- Improved formatting with better headings and structure
- Fixed placeholder syntax for file protocol references
- Added clearer instructions and fixed inconsistencies 
- Removed unused outdated test class (test_history_service.py)
- Updated documentation to reference psycopg2_binary instead of psycopg2 for the history service
The most significant changes are in the orchestrator prompt formatting and structure to improve readability while maintaining the same functionality.
> FIX: Enhanced system prompt with latest history changes

- src/orchestrator/orchestrator_main.py
Hotfix for a bug with removing agents
Don't modify a dictionary while iterating over it.
> Fixed a bug

- pyproject.toml
Update the dependencies to pick up the lasted connector releases
Updated version in pyproject.toml
> AI-776: Update connectors to latest release version

- docs/docs/documentation/tutorials/sql-database.md
Make the SQL tutorial easier
Download a zip file from github directly rather than trying to download a directory. Improve the organization of the steps.
> AI-755: Made a few changes to the SQL tutorial to make it easier to run

- tests/test_orchestrator_streaming_output.py
> AI-781 : Remove the skip condition since tests are fixed

- README.md
- docs/docs/documentation/getting-started/installation.md
> (Merge dev into main) Update readme and docs to say 3.10.16 instead of 3.10 (#97)

- .gitignore
- cli/commands/init/check_if_already_done.py
- cli/commands/init/init.py
- cli/commands/init/web_init_step.py
- cli/main.py
- config_portal/frontend/app/components/steps/BuiltinAgentSetup.tsx
- config_portal/frontend/app/components/steps/CompletionStep.tsx
- docs/docs/documentation/concepts/cli.md
- docs/docs/documentation/getting-started/quick-start.md
Update docs for init gui and add --use-web-based-init flag. Added a new step for web init to fit it in better with the existing flow.It also has a small refactor for the [BuiltinAgentSetup.tsx](https://github.com/SolaceLabs/solace-agent-mesh/compare/dev...rohan/init-gui-improvements?expand=1#diff-9a980f5f7bfd72ce264eb8523c9ca6d730ad5efc1ab304c14f2d7068e402adfd) component.
> AI-787 : Update docs for init gui and add --use-web-based-init flag

- cli/commands/init/init.py
> AI-804: Fix init --skip 

- docs/docs/documentation/tutorials/bedrock-agents.md
- docs/docs/documentation/tutorials/slack-integration.md
- docs/docs/documentation/tutorials/sql-database.md
This change adds comprehensive tutorial documentation for the Amazon Bedrock Agents and Flows plugin integration with Solace Agent Mesh (SAM). The documentation enables users to leverage AWS AI capabilities through Bedrock within the SAM framework.
- Added tutorial documentation for Amazon Bedrock Agents & flows plugin
- Created a detailed step-by-step guide covering setup, configuration, testing, and troubleshooting
- Adjusted sidebar positions of existing tutorials to accommodate the new documentation
Please verify technical accuracy of the AWS Bedrock integration details and ensure the instructions align with current AWS and SAM implementation practices.
> AI-794: Added tutorial documentation for Amazon Bedrock Agents & flows plugin

- src/orchestrator/components/orchestrator_stimulus_processor_component.py
- src/services/llm_service/components/llm_request_component.py
Proper handling of Timeout Errors
Implement try/catch logic and re-invoking orchestrator
> AI-731: Fix timeout error stuck in infinite retry loop 

- .github/helper_scripts/build_frontend.py
To fix the Docker build process by correctly building all frontend components of the application, including both the config portal and web-visualizer.
- Docker build patch: Updated the build script to build both frontend components sequentially, first navigating to the config_portal/frontend directory and then to the web-visualizer directory to run npm install and build commands for each.
Verify that both frontend components build correctly in the Docker environment and that the directory navigation logic works as expected.
> DOCKER: Docker build patch

- .github/workflows/release.yml
- Use latest tag for versioning
> DATAGO-101491: Get version from tag

- config_portal/backend/server.py
- config_portal/frontend/app/components/steps/BrokerSetup.tsx
Verify broker connection in init gui, so that users know if they entered the wrong credentials.
> AI-815: Verify broker connection in init gui

- src/common/mysql_database.py
- src/services/history_service/history_providers/sql_history_provider.py
Remove LIMIT from query since session_id is already a primary key.
> DATAGO-102790: Long History PostgreSQL Error

- .github/actions/push-docker/action.yml
- .github/workflows/push-docker.yml
- .github/workflows/release.yml
- Fix release docker action to properly fetch tags 
- Add a manual workflow for pushing the image
> DATAGO-103349: fix docker release

- client/webui/frontend/src/lib/components/chat/ChatInputArea.tsx
- client/webui/frontend/src/lib/components/chat/ChatSidePanel.tsx
- client/webui/frontend/src/lib/components/chat/SessionSidePanel.tsx
- client/webui/frontend/src/lib/components/chat/artifact/ArtifactDeleteAllDialog.tsx
- client/webui/frontend/src/lib/components/chat/artifact/ArtifactDetails.tsx
- client/webui/frontend/src/lib/components/chat/artifact/ArtifactMorePopover.tsx
- client/webui/frontend/src/lib/components/chat/artifact/ArtifactPanel.tsx
- client/webui/frontend/src/lib/components/chat/file/FileMessage.tsx
- client/webui/frontend/src/lib/components/navigation/NavigationButton.tsx
- client/webui/frontend/src/lib/components/pages/ChatPage.tsx
- client/webui/frontend/src/lib/components/ui/ViewWorkflowButton.tsx
- client/webui/frontend/src/lib/components/ui/button.tsx
- client/webui/frontend/src/lib/components/ui/chat/chat-bubble.tsx
- client/webui/frontend/src/lib/components/ui/toast-container.tsx
- client/webui/frontend/src/lib/contexts/ChatContext.ts
- client/webui/frontend/src/lib/hooks/useArtifacts.ts
- client/webui/frontend/src/lib/providers/ChatProvider.tsx
Porting over changes from internal repo, including:
1. Using styled tooltips instead of titles
2. Adding a delete all action in the artifact panel
3. Refreshing the artifact list when a new file is returned
Changes to frontend code
n/a
> DATAGO-106990: porting chat updates

- client/webui/frontend/src/lib/components/chat/artifact/ArtifactDeleteAllDialog.tsx
- client/webui/frontend/src/lib/components/chat/artifact/ArtifactDeleteDialog.tsx
- client/webui/frontend/src/lib/components/chat/artifact/ArtifactMorePopover.tsx
- client/webui/frontend/src/lib/components/chat/artifact/ArtifactPanel.tsx
- client/webui/frontend/src/lib/providers/ChatProvider.tsx
No functional change. Updating UI labels in the artifact panel from "artifacts" to "files" for consistency.
Text changes
n/a
> DATAGO-106990: chore - changing UI labels from artifact to file

- client/webui/frontend/src/lib/components/activities/FlowChartPanel.tsx
The current auto-fit behavior of the workflow diagram causes the UI to snap to the center on every new render after adding a new element. This can be frustrating for users who are trying to view other parts of the diagram.
This change stops auto fit-view in flowchart once there is user interaction. 
Add a new state `hasUserInteracted` that is set to `true` if user has interaction (click on node or edge, zoom or pan), and reset to `false` if `taskId` changes. Only call `fitview`() if `hasUserInteracted` is false.
`onMoveStart` can be triggered by initial `fitview`(), so adding `event.isTrusted` condition is necessary for real user action.
> DATAGO-106770: Stop auto fit-view in flowchart once there is user interaction

- Dockerfile
- cli/commands/plugin_cmd/catalog_cmd.py
- config_portal/backend/plugin_catalog_server.py
- config_portal/backend/server.py
- docs/docs/documentation/concepts/plugins.md
- docs/docs/documentation/deployment/deploy.md
- docs/docs/documentation/getting-started/quick-start.md
> DATAGO-107248:fix for containerized configuration and deployment and related docs improvements

- .github/workflows/release.yml
Remove slack notification profile from release action to unblock release action.
> DATAGO-107598: Remove slack notification profile from release action

- cli/commands/init_cmd/orchestrator_step.py
- client/webui/frontend/src/lib/components/chat/ChatInputArea.tsx
- client/webui/frontend/src/lib/components/chat/ChatMessage.tsx
- client/webui/frontend/src/lib/components/chat/file/FileMessage.tsx
- config_portal/frontend/app/components/steps/init/OrchestratorSetup.tsx
- examples/a2a_orchestrator.yaml
This PR:
* Updates Orchestrator text for docs review
* Ensures user uploaded files will wrap to the next line
* Ensures focus is returned to chat area after a user has selected files to upload.
> DATAGO-107381: updating messaging for docs review and improving file input

- .github/workflows/ci.yaml
- .github/workflows/cleanup_ws.yaml
- .github/workflows/push-docker.yml
- .github/workflows/release.yml
Add prisma checks 
Add Whitesource cleanup workflow
Push ECR image on push
> DATAGO-107284: Add prisma

- src/solace_agent_mesh/agent/adk/callbacks.py
Added more instructions for when to create text based artifacts, it should avoid cases where it goes and creates a comprehensive artifact for a simple query
> DATAGO-107231: Improve artifact creation

- .gitignore
- README.md
Updating gitignore and fixing typos in README
> chore(DATAGO-110248): readme updates

- examples/gateways/webui_example.yaml
- preset/agents/basic/webui.yaml
- templates/webui.yaml
Before (returning variable names by default):
After (return default values):
> DATAGO-110625: example web ui agent is returning odd configuration

- cli/commands/eval_cmd.py
- evaluation/message_organizer.py
- evaluation/run.py
- evaluation/subscriber.py
- evaluation/summary_builder.py
- examples/agents/a2a_agents_example.yaml
- tests/evaluation/config.json
- Fixed evaluation post-refactoring
- Added check for sam-rest-gateway installed
- Improved readiness check
> chore(DATAGO-110404): Update Evaluation post-A2A refactor

- src/solace_agent_mesh/agent/adk/artifacts/filesystem_artifact_service.py
Ensuring that the write of artifacts to disk are fully flushed and fsynced to disk before returning
> chore(DATAGO-111516): fsync artifacts to disk before returning

- .dockerignore
- .github/workflows/ci.yaml
- Dockerfile
This pull request introduces significant improvements to the Docker build process and related configuration files, focusing on optimizing image builds, improving caching, and enhancing platform support. The changes streamline dependency installation, introduce multi-stage builds for better caching and smaller images, and update CI workflows to build the correct platform targets based on branch context.
**Dockerfile refactor and build optimization:**
* Refactored `Dockerfile` to use multi-stage builds (`base`, `builder`, `runtime`), improving layer caching and reducing final image size by separating system dependencies, Python wheels, and runtime setup. Playwright installation is optimized for caching and installed early.
* System dependencies (including `ffmpeg` and Node.js) are now …
> ci(DATAGO-112688): Improve CI build times - arm64 builds in default branch + docker caching strategies

- client/webui/frontend/src/lib/components/chat/ChatMessage.tsx
- client/webui/frontend/src/lib/components/chat/artifact/ArtifactBar.tsx
- client/webui/frontend/src/lib/components/chat/artifact/ArtifactCard.tsx
- client/webui/frontend/src/lib/components/chat/file/ArtifactMessage.tsx
- client/webui/frontend/src/lib/components/chat/file/FileIcon.tsx
- client/webui/frontend/src/lib/components/pages/ChatPage.tsx
- client/webui/frontend/src/lib/providers/ChatProvider.tsx
This pull request primarily refactors and improves the UI code for chat messages and artifact bars in the frontend. The main focus is on code style consistency, UI polish, and minor error handling enhancements, especially in the `ArtifactBar` component. No significant new features are introduced, but the code is cleaner, more maintainable, and visually more consistent.
**UI and Code Style Improvements:**
* Refactored JSX in `ChatMessage.tsx` and `ArtifactBar.tsx` to use more concise, single-line components, improving readability and reducing visual clutter. [[1]](diffhunk://#diff-f9b9a25a941b9debe58c474838e457efe96c638ee37362656c18e86024aca620L76-R81) [[2]](diffhunk://#diff-f9b9a25a941b9debe58c474838e457efe96c638ee37362656c18e86024aca620L246-R226) …
> chore: tidying styles
